### ISSUE TITLE
login button still visible after sign in due to error in login.html page script line 40 

### ISSUE THREAD

**Issue by mdjolieca** [udacity/ud330#51]
https://github.com/udacity/ud330/blob/master/Lesson4/step2/templates/login.html#L40
Change this line  
    $('#signinButton').attr('style', 'display: none');

to this one
 $('#signInButton').attr('style', 'display: none');

**Comment by veronikabenkeser** [comment]
Thank you for bring this to our attention! We fixed this bug and are working hard to fix other bugs in our code in order to provide our students with the best possible learning experience. Happy Learning!
